services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    depends_on: [mongo]
    ports: ["3000:3000"]
volumes:
  mongo_data: {}
